all: MCSOS

MCSOS:
	javac Disk.java Printer.java ResourceManager.java FileInfo.java DirectoryManager.java DiskManager.java PrinterManager.java PrintJobThread.java UserThread.java MCSOS.java
	java MCSOS

clean:
	rm *.class
	rm PRINTER/*