main: MusicLibrary.cpp
	echo     ------------compiling main.cpp to create executable program main----------------
	#g++  -ggdb   -std=c++11   MusicLibrary.cpp   -o   MusicLibrary
	g++ MusicLibrary.cpp -o MusicLibrary


