main: main.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   main.cpp   -o   string
	@echo     ------------Congratulation to you! Successfully compile.
	@echo     ------------"./string" to run

