main: main.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   main.cpp   -o   roman
	@echo     ------------Congratulation to you! Successfully compile.
	@echo     ------------Run manually by :
	@echo     ------------"./roman < input > outout"

clean:
	rm -rf roman roman.dSYM roman.o
