main: main.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   main.cpp   -o   parseCmd
	@echo     ------------Congratulation to you! Successfully compile.
	@echo     ------------input "(history | ./parseCmd > BashTokens)" to parse all history command on screen;
	@echo     ------------input "(cat [filename] | ./parseCmd > BashTokens)" to parse all history command on screen, eg.:
	@echo     ------------"cat input | ./parseCmd > BashTokens"