main: main.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   main.cpp   -o   urlParse
	@echo     ------------Congratulation to you! Successfully compile.
	@echo     ------------Run manually by :
	@echo     ------------"./urlParse < urltest.txt"