main: main.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   main.cpp   -o   parseC
	@echo     ------------Congratulation to you! Successfully compile.
	@echo     ------------input "(./parseC < 1_musicLibrary.cpp > tokens)" to parse cpp, or all history command on screen.
	@echo     ------------input "(diff 1_demo_output_musicLibrary.cpp tokens)" to check the diff to screen, if no output, then right.