main: main.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   main.cpp   -o   testIntegers
	@echo     ------------Congratulation to you! Successfully compile.
	@echo     ------------"./testIntegers < numbers > myNumbers" to run

