main: MusicLibrary.cpp
	@echo     ------------compiling main.cpp to create executable program main----------------
	g++  -ggdb   -std=c++11   MusicLibrary.cpp   -o   MusicLibrary
	@echo     ------------Congratulation to you! Successfully compile.Use \"./MusicLibrary [MusicLibraryName]\" to run, for example:
	@echo     ------------Command: i,p,d,l,q.


